#!/bin/bash
[ $# -eq 4 ] || { echo "$0 INPUT_FILE START_TIME END_TIME OUTPUT_FILE" && exit 1; }
[ $2 == "start" ] && { echo start; ffmpeg -i $1 -to $3 $4; exit 0; }
[ $3 == "end" ] && { echo end; ffmpeg -i $1 -ss $2 $4; exit 0; }
ffmpeg -i $1 -ss $2 -to $3 $4
