#!/bin/bash
# Can use "start" and "end" for START_TIME and END_TIME
[ $# -eq 4 ] || { echo "$0 INPUT_FILE START_TIME END_TIME OUTPUT_FILE" && exit 1; }
[ $2 == "start" ] && { echo start; ffmpeg -i $1 -to $3 -c:v copy -c:a copy $4; exit 0; }
[ $3 == "end" ] && { echo end; ffmpeg -i $1 -ss $2 -c:v copy -c:a copy $4; exit 0; }
ffmpeg -i $1 -ss $2 -to $3 -c:v copy -c:a copy $4
